### ISSUE TITLE
[Docker Hub] Audit logging

### ISSUE THREAD

**Issue by pkennedyr** [docker/roadmap#1]
**Tell us about your request**
View actions performed against a repository by members of an organization, including who performed the action, what the action was, and when it was performed. This also includes an API to retrieve audit information.

**Which service(s) is this request for?**
Docker Hub

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Docker Hub customers have cited a desire to audit all the pull, push, delete and other activities related to a company repo for security monitoring (see https://github.com/docker/hub-feedback/issues/761). 

**Are you currently working around this issue?**
N/A

**Additional context**
N/A

**Attachments**
N/A

**Comment by piroux** [comment]
This feature is currently listed in the [Docker Hub "Team" plan](https://www.docker.com/pricing).

![Screenshot from 2021-01-21 10-42-26](https://user-images.githubusercontent.com/438492/105332905-6aa08b00-5bd5-11eb-85d3-c556a60b2a87.png)

But I cannot find any mention of it on any pages of the Docker hub web frontend.
Moreover, trying to find other occurrences, in articles or documentation pages, across the entire docker.com domain [does not return any convincing results](https://www.google.com/search?q=site%3Adocker.com+-site%3Ahub.docker.com+%22audit+log%22).

With an active Docker Hub "Team" plan subscription, is there something to activate in order to access this Audit Log feature ? Or is it already there and I missed it ?
Or is it / will it be available through the [Developer Preview Program](https://www.docker.com/community/get-involved/developer-preview) first before being available to all Docker Hub "Team" subscribers ?

**Comment by piroux** [comment]
Great !! I guess it was in Santa Claus's sack :santa: 

https://www.docker.com/blog/new-docker-reporting-provides-teams-with-tools-for-higher-efficiency-and-better-collaboration/

**Comment by nebuk89** [comment]
Shipped! If you have ideas of features you would like to see please open new feature requests 🎉
