### ISSUE TITLE
[GitHub Action] Upgrade to buildx

### ISSUE THREAD

**Issue by chris-crone** [docker/roadmap#122]
**Tell us about your request**
The Docker GitHub Action currently uses the features provided by `docker build`. Faster builds are accessible by using BuildKit but this requires setting an environment variable which is not obvious to most users. Building multi arch images is currently not possible. This proposes moving the GitHub Action to use buildx which provides these features out of the box.

**Which service(s) is this request for?**
This is for the Docker GitHub Action which can be found [here](https://github.com/marketplace/actions/build-and-push-docker-images). Source code for the Action can be found [here](https://github.com/docker/build-push-action).

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
* Using BuildKit for faster builds
* Building multiarch images

**Are you currently working around the issue?**
N/A

**Additional context**
More technical details can be found on the [Docker GitHub Action's issue tracker](https://github.com/docker/build-push-action/issues/71).

**Comment by crazy-max** [comment]
See also build-push-action#71

**Comment by christian-weiss** [comment]
I just want to show some love for this issue - i hope it motivates you to finish it soon. 

For the very first release of the Github Action (`docker build`-based) the team had looked around for examples in the wild.

One example (not Github-based, but Dockerhub-based):
I would love to see this project building its `buildx`-based Dockerfile on Github with your Github Action instead of on Dockerhub: https://github.com/CBrosius/icinga2/blob/master/Dockerfile.arm32v7 / https://github.com/CBrosius/icinga2/blob/master/multi-arch-manifest.yaml

So your `buildx-based pimped Github Action is warm welcomed.
