### ISSUE TITLE
[Feature Request]: generating SBOMs for container images while building them

### ISSUE THREAD

**Issue by developer-guy** [docker/roadmap#274]
I'm a huge fan of the `bake` command, recently I opened a similar issue to the builds which you can see from [here](https://github.com/docker/buildx/issues/778).

Nowadays, SBOM (Software Bill Of Materials) is a trending topic. So, we thought that maybe we can support this `SBOM` generation as a separate `target` within the `docker-bake.hcl`. There are many alternatives to generate SBOMs.  

* https://github.com/anchore/syft
* https://github.com/spdx/spdx-sbom-generator
* https://github.com/tern-tools/tern
* https://github.com/kubernetes/release/tree/master/cmd/bom
* https://github.com/CycloneDX/cyclonedx-cli

So, we can pick from one of these to generate SBOMs while building container images.

cc: @luhring @nishakm @puerco @Dentrax @imjasonh 🥳🙋🏻‍♂️

**Comment by justincormack** [comment]
@coderpatros by "useful SBOM for the Docker tooling itself" do you mean inputs that Docker already knows about, like base layers? I totally agree that there is a difficult mix of things in Docker builds, potentially arbitrary shell scripts and network access, and so we are going to have to use a mix of methods.

People building tools, one question I have is what hooks would be useful to you? If we have to plumb data through (input SBOMs from base, input SBOMs from added software, analysed parts) what kind of hooks would make this easier for your tools?

**Comment by coderpatros** [comment]
@justincormack I mean an SBOM that describes, as an example, the Docker CLI.

**Comment by tianon** [comment]
This is very interesting :smile:

I think anything that happens in `docker build` by default would make me a little wary (given the potential overhead of deep calculation/inspection of things like packages inside the image), however I think there'd be a ton of value in optionally including more of the `Dockerfile`/build context data somehow.

Some of the data that's really difficult to get after the fact that Docker itself is uniquely suited to provide are exact image IDs/digests or even locations/names for base images and information about the _other_ build stages that helped create the final image.  For example, the specific `openjdk` tag/digest I used to build `my-application.jar` is very relevant information for that final `my-application.jar` artifact.

There are a lot of blurrly lines here depending on how deep a user might want metadata, and the degree of data is probably going to change the "calulcation/information gathering overhead" pretty signifcantly and for users building closed-source solutions, potentially *too much* information, leaking things they didn't want to, like details about their source code, internal container registry, or worse.

(I guess what I'm trying to get at there is that all aspects of this probably need to be opt-in?)

For my own use cases, I don't think I'd want this to happen during `docker build` itself unless it was very, very fast (so that it's not in the critical path for build/push).

To illustrate a bit better, a full clean build of all the variants of https://hub.docker.com/_/python already takes several hours per architecture, even on a reasonably fast machine, so having the SBOM calculated out-of-band could be pretty dramatic.

**Comment by imjasonh** [comment]
> Some of the data that's really difficult to get after the fact that Docker itself is uniquely suited to provide are exact image IDs/digests or even locations/names for base images and information about the _other_ build stages that helped create the final image. For example, the specific `openjdk` tag/digest I used to build `my-application.jar` is very relevant information for that final `my-application.jar` artifact.

See https://github.com/docker/roadmap/issues/243 for a concrete proposal toward this goal.

**Comment by nishakm** [comment]
> People building tools, one question I have is what hooks would be useful to you? If we have to plumb data through (input SBOMs from base, input SBOMs from added software, analysed parts) what kind of hooks would make this easier for your tools?

A few things come to mind for me:
1. A record of the base image in the "created_by" field or a dedicated field in the config.
2. A record of build argument values (although this would close the option of passing secrets via the build arguments, I personally believe this is a good thing)
3. Some option in `docker build` for a SBOM generation tool to [access the mountpoint](https://github.com/vmware-samples/containers-with-sboms/blob/e90e84707e3695069f05adee5de332a01ac17dbe/base_container.sh#L23)
4. Some ability to include or reuse SBOMs created externally
5. Some ability to record the state of intermediate containers during a multi-stage docker build (this is a pet peeve of mine as this is the bit that most container builders tell me is impossible to do using docker now)

To @imjasonh's point of recording the base image: To make it easier for tools to parse this information, it would be nice to record the base images all the way to scratch. For example, there are multiple base images that have contributed to the final `golang` image.
<img width="1819" alt="Screen Shot 2021-11-03 at 10 28 00 AM" src="https://user-images.githubusercontent.com/1007786/140156569-66845936-ca5b-40c3-ab96-2ab55c86e2a2.png">

As for the shell script parsing, some environment variable substitution would help greatly. Tern [currently tries to do this](https://github.com/tern-tools/tern/blob/main/tern/analyze/default/dockerfile/parse.py) with some success.
