### ISSUE TITLE
Image Access Management - Allow Specific Images in Restricted Categories 

### ISSUE THREAD

**Issue by MercedesSteele** [docker/roadmap#370]
**Tell us about your request**
As an admin, when my team is in the development/testing process, they want to use specific images in a category currently listed as restricted. I would like the option to whitelist images in a restricted category therefore my team is able to continue working with approved images.

**Which service(s) is this request for?**
Image Access Management

**Comment by jorsmatthys** [comment]
We want the same feature for our Enterprise. At the moment we would have to enable all community images because developers need only a few images for automated testing during  builds which is certainly not what we want. Having to push a copy of every image we need to a private repository is cumbersome as well. 

Having access control features was one of the main criteria that led us to opt for the more expensive docker business licenses at our Enterprise, so it is very important to us to see this feature evolve in the direction we expected it to.

**Comment by Bkblodget** [comment]
Closing this ticket because it is a duplicate. You can follow the progress of this functionality in the new ticket here: [Private Image marketplace](https://github.com/docker/roadmap/issues/625)
