### ISSUE TITLE
Please Provide a repo for Fedora 39

### ISSUE THREAD

**Issue by hhlp** [docker/roadmap#536]
[x] This is a feature request

I searched existing issues before opening this one The Docker-CE Fedora repository is the recommended way to install it. It has many benefits over installing from a package or any other method.

COMMENT

Fedora also releases a new version every six months. The Fedora repository also takes a very long time to become ready after the release of a new version, with many issues being opened after each recent Fedora is released.

Fedora has officially branched Version 39 might have a beta release on — Tue 2023-09-19 and the Final Version Will be ready Tue 2023-10-24.

I'm filing this issue to hopefully put this task on the radar so that there might be a repository set up in time for the Fedora 39 release cycle...

NOTE

Some of us migrate when the beta version is ready so we have to disable the repository and wait for it to be ready

REFERENCES

Release Schedule: https://fedorapeople.org/groups/schedule/f-39/f-39-key-tasks.html

Regards.,

**Comment by thaJeztah** [comment]
We try to provide packages as soon as possible; however, we depend on the Fedora project to provide images, as our release process uses Docker images to build the packages.

We have a PR pending for containerd packages for Fedora 39 since April;

- https://github.com/docker/containerd-packaging/pull/315

However, the Fedora images are currently still "half-way", and still contain "rawhide" bits, which breaks the builds; see

- https://github.com/docker/containerd-packaging/pull/325

Once the images are in a usable shape, we can include Fedora 39 in the next patch releases of the containerd and docker packages.

**Comment by thaJeztah** [comment]
Small update; the fedora maintainers published images for Fedora 39 (now no longer "rawhide"), which means that we can include Fedora 39 in the next patch release of Docker Engine. We will be publishing containerd.io packages soon (which is the first package needed).


I will close this ticket here on the roadmap, as packaging of the open-source packages is a bit out of scope here, but we can continue the conversation (closing it just for housekeeping 😄)
