### ISSUE TITLE
eclipse-temurin:17-jre-alpine vulnerabilities

### ISSUE THREAD

**Issue by zopahima** [docker/roadmap#675]
eclipse-temurin:17-jre-alpine image contains multiple **old** vulnerabilities, is there any plan to address them in the near future? when can expected to get a patched version?
vul scan taken by trivy scanner.

![image](https://github.com/docker/roadmap/assets/164059200/1ce59427-72ab-4fde-9000-a5c3106320ac)

**Comment by thaJeztah** [comment]
The `eclipse-temurin` image is maintained by Adoptium; see the support links on the readme; https://hub.docker.com/_/eclipse-temurin

It looks like the best location to report issues with that image is https://github.com/adoptium/containers/issues

i'll close the ticket here, but feel free to continue the conversation

**Comment by zopahima** [comment]
@thaJeztah  Thanks for the update. 
According to the conversation here - https://github.com/adoptium/containers/issues/576, it seems that alpine:3.20 has already been merged into temurin and it's only a matter of time until it gets to DockerHub.
Is there any ETA for the DockerHub update?

**Comment by thaJeztah** [comment]
@zopahima After upstream has updated the images / dockerfiles, the reference for the official images needs to be updated in the https://github.com/docker-library/official-images repository (which, once merged, will put rebuilding / updating the image on Docker Hub in the queue).

The refernce for the `eclipse-temurin:17-jre-alpine` image can be found here; https://github.com/docker-library/official-images/blob/98b96adc6f1d31fd1e69029e61a0e3bd56e95e43/library/eclipse-temurin#L304-L307, and that reference was last updated two months ago in https://github.com/docker-library/official-images/commit/3db9ea793dcd38253c87694a15b192b71e3ac58f (https://github.com/docker-library/official-images/pull/16649)

Looking at the commit that it was updated to; https://github.com/adoptium/containers/commit/057e5aa7581e96b8a2334290e750b329d62abfdf, it looks like that's behind their latest changes and is missing the alpine update; here's the diff with their current "main" branch; https://github.com/adoptium/containers/compare/057e5aa7581e96b8a2334290e750b329d62abfdf...304f1823b4a96a4a7b988519d4b623d46bb73d6f

So for the image to be updated, the reference in https://github.com/docker-library/official-images needs to be updated to include the alpine 3.20 changes; I don't see a PR pending for that, so that's something they would need to do; https://github.com/docker-library/official-images/pulls?q=is%3Apr+eclipse-temurin+in%3Atitle+is%3Aopen

**Comment by omerf-hmcts** [comment]
You will never find an image that has 0 vulnerability. I suggest you focus on Critical and High , 2 Low and 8 Medium is a good number. Also Docker hub, you can track vulnerabilities.

![ScreenShot-2024-06-13-16-30-41@2x](https://github.com/docker/roadmap/assets/119492016/aeda1613-0890-416e-98e0-37311776bea4)
