### ISSUE TITLE
Issues with the Docker Hub API becoming unresponsive

### ISSUE THREAD

**Issue by zhaoshouli** [docker/roadmap#756]
When accessing the URL https://hub.docker.com/api/content/v1/products/search?q=%2B&source=community&type=image&page=1&page_size=100, a 503 error is displayed. Is there a new API available, or is the service undergoing maintenance or updates?

**Comment by nicks** [comment]
I think we shut this route down recently. @benja-M-1 do you know if we have a publicly documented alternative?

**Comment by benja-M-1** [comment]
Hi @zhaoshouli thank you for reaching out. 
This URL is part of an endpoint that has been deprecated some years ago. We have finally taken the time to clean it up. Since we saw some traffic to it we issued brownouts for the last few weeks: the endpoint was returning a 410 for 1, 6 and 12 hours.

You can switch to the most recent API: `https://hub.docker.com/api/search/v4`.
The query parameters would now be:
- `query` instead of `q` 
- `badges=none` instead of `source=community`
- `size=100` instead of `page_size=100` 
- `from=200` instead of `page=2` (if `size` is 100)

Out of curiosity, @zhaoshouli  can you tell us why you are using this endpoint?

**Comment by benja-M-1** [comment]
Note that, from now on, the URL will return a 200 with an empty response. We did that because we noticed that the automated tools still using the endpoint were aggressively retrying on the endpoint. So to avoid this and being DoSed, for the moment we return an empty JSON response. But we might transition to a 410 soon.
