### ISSUE TITLE
Anti-Abuse Rate Limits

### ISSUE THREAD

**Issue by 412PIT** [docker/roadmap#87]
**Tell us about your request**
In May 2020, we will implement new rate limits for anonymous pulls in Docker Hub on a per IP basis. This initial rate limit will (a) only apply to non-authenticated pulls (anonymous), (b) be set at 20,000 pulls per 6 hour window. If you are authenticated, there will be no rate limit at this time. 

**Which service(s) is this request for?**
Docker Hub, Docker CLI

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
This rate limit is being put in place as a service anti-abuse measure. We have observed certain IPs pulling in excess of 60,000 times per 6 hour window.

**Comment by crazy-max** [comment]
@412PIT I wonder if this is related to [Diun](https://github.com/crazy-max/diun). It allows to watch a Docker repository and report new tags with notifications.

Under the hood the application will list tags via the registry API and check the manifest of each one. The layers are not pulled but I'm wondering if the hits you see are not due to the download of the JSON manifest. Diun uses a user-agent that looks like `diun/2.0.0 go/1.14.2 Linux` if you can check the access logs of the registry.

**Comment by justincormack** [comment]
@crazy-max I don't think so, we haven't identified a single user agent causing the issue. We do not get a lot of traffic from diun user agents.

**Comment by pkennedyr** [comment]
[**UPDATE**] Docker's Terms of Use have been updated to reflect new limits on the number of image pulls. 

Starting November 1, 2020:

- Anonymous users will have an upper limit of 100 image pulls in a six hour period
- Accounts authenticated with a DockerID will have an upper limit of 200 image pulls in a six hour period
- Pro and Team subscriptions do not have limits

For additional details, please see the [FAQ](https://www.docker.com/pricing/resource-consumption-updates) and our recent blog post regarding the [pull rate limit policy](https://www.docker.com/blog/scaling-docker-to-serve-millions-more-developers-network-egress/).

If you have a free account, you may upgrade to a Pro or Team subscription [here](https://www.docker.com/pricing).

The updated Docker Terms of Service are available [here](https://www.docker.com/legal/docker-terms-service).

**Comment by justincormack** [comment]
These (very high) limits are in production now.
